### model
model_name_or_path: saves/test/101/latest/model  # pretrain_ckp/gemma1.3/
adapter_name_or_path: saves/test/110/latest,saves/test/101/latest
resume_from_checkpoint: saves/test/111/checkpoint-5
### method
stage: pt
do_train: true
finetuning_type: model_lora
lora_target: q_proj,v_proj
lora_rank: 64

ddp_timeout: 180000000
### dataset
tokenized_path: pretrain_token/,pretrain_token/
# dataset_dir: data/c4_test
# dataset: c4_demo
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 32
# packing: true

### output
output_dir: saves/test/111
logging_steps: 10
save_steps: 5
save_total_limit: 2
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 2000
fp16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 1000

report_to: none
